<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights Two'),
  'icon' => 'gsb-insights-two.png',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-two',
  'css' => 'gsb-insights-two.css',
  'regions' => array(
    'contentone' => t('Full Header'),
    'contenttwoone' => t('Column one'),
    'contenttwotwo' => t('Column two'),
    'contentthreeone' => t('Column one'),
    'contentthreetwo' => t('Column two'),
    'contentthreethree' => t('Column three'),
    'contentthreefour' => t('Column four'),
  ),
);
