<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights B'),
  'icon' => 'gsb-insights-b.jpg',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-b',
  'css' => 'gsb-insights-b.css',
  'regions' => array(
    'contentone' => t('Row A'),

    'contenttwoone' => t('Row B column 1'),
    'contenttwotwo' => t('Row B column 2'),

    'contenttwothree' => t('Row B column 3'),

    'contentthreeone' => t('Row C column 1'),
    'contentthreetwo' => t('Row C column 2 alpha'),
    'contentthreethree' => t('Row C column 2 beta'),
    'contentthreefour' => t('Row C column 3 gamma'),

    'contentfourone' => t('Row D column 1'),
    'contentfourtwo' => t('Row D column 2'),
    'contentfourthree' => t('Row D column 3'),
    'contentfourfour' => t('Row D column 4'),

    'contentfiveone' => t('Listing row')
  ),
);
