<?php
$plugin = array(
  'title' => t('GSB Front page'),
  'icon' => 'gsb-front-page.png',
  'category' => t('Panopoly'),
  'theme' => 'gsb-front-page',
  'css' => 'gsb-front-page.css',
  'regions' => array(
    'contentslider' => t('Slider'),
    'sidebarnavigation' => t('Sidebar Navigation'),
    'featuredcolone' => t('Featured column 1'),
    'featuredcoltwo' => t('Featured column 2'),
    'featuredcolthree' => t('Featured column 3'),
    'footercolone' => t('Footer column 1'),
    'footercoltwo' => t('Footer column 2'),
    'footercolthree' => t('Footer column 3'),
  ),
);
