<?php
$plugin = array(
  'title' => t('GSB Front page'),
  'icon' => 'gsb-front-page.png',
  'category' => t('GSB'),
  'theme' => 'gsb-front-page',
  'css' => 'gsb-front-page.css',
  'regions' => array(
    'contentslider' => t('Slider'),
    'sidebarnavigation' => t('Program links'),
    'featuredcolone' => t('Image CTA'),
    'featuredcoltwo' => t('Social feed'),
    'featuredcolthree' => t('Upcoming events'),
  ),
);
