<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights C'),
  'icon' => 'gsb-insights-c.png',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-c',
  'css' => 'gsb-insights-c.css',
  'regions' => array(
    'contentone' => t('Row A'),

    'contenttwoone' => t('Row B column 1'),
    'contenttwotwo' => t('Row B column 2'),

    'contentthreeone' => t('Row C column 1'),
    'contentthreetwo' => t('Row C column 2'),
    'contentthreethree' => t('Row C column 3'),
    'contentthreefour' => t('Row C column 4'),
  ),
);
