<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Full Bleed Home Page'),
  'icon' => 'gsb-full-bleed-home-page.png',
  'category' => t('GSB'),
  'theme' => 'gsb-full-bleed-home-page',
  'regions' => array(
    'full_bleed_header' => t('Full Bleed Header'),
    'top_full' => t('Top Full'),
    'top_left_third' => t('Top Left Third'),
    'top_center_third' => t('Top Center Third'),
    'top_right_third' => t('Top Right Third'),
    'top_left' => t('Top Left'),
    'top_right' => t('Top Right'),
    'middle_gray_full' => t('Middle-Gray Full'),
    'middle_gray_left' => t('Middle-Gray Left'),
    'middle_gray_right' => t('Middle-Gray Right'),
    'middle_green_full' => t('Middle-Green Full'),
    'middle_green_left' => t('Middle-Green Left'),
    'middle_green_right' => t('Middle-Green Right'),
    'bottom_full' => t('Bottom Full'),
    'bottom_left' => t('Bottom Left'),
    'bottom_right' => t('Bottom Right'),
    'last_full' => t('Last Full'),
  ),
);
