<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Business insights'),
  'icon' => 'gsb-business-insights.png',
  'category' => t('Panopoly'),
  'theme' => 'gsb-business-insights',
  'css' => 'gsb-business-insights.css',
  'regions' => array(
    'contentrightone' => t('Right column'),
    'contentoneone' => t('Full width'),
    'contenttwoone' => t('Column one'),
    'contenttwotwo' => t('Column two'),
    'contenttwothree' => t('Column three'),
    'contentthreeone' => t('Full width'),
    'contentfourone' => t('Column one'),
    'contentfourtwo' => t('Column two'),
    'contentfourthree' => t('Column three'),
    'contentfiveone' => t('Full width'),
  ),
);
