<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights A'),
  'icon' => 'gsb-insights-a.jpg',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-a',
  'regions' => array(
    'contentone' => t('Feature'),

    'contenttwoone' => t('Row B wide'),
    'contenttwotwo' => t('Row B narrow'),
    'contenttwothree' => t('Row B narrow'),

    'contentthreeone' => t('Row C narrow'),
    'contentthreetwo' => t('Row C narrow'),
    'contentthreethree' => t('Row C wide'),

    'contentfourone' => t('Row D narrow'),
    'contentfourtwo' => t('Row D wide'),
    'contentfourthree' => t('Row D narrow'),

    'contentfiveone' => t('Row E narrow'),
    'contentfivetwo' => t('Row E narrow'),
    'contentfivethree' => t('Row E narrow'),
    'contentfivefour' => t('Row E narrow'),

    'contentsixone' => t('Listing')
  ),
);
