<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights A'),
  'icon' => 'gsb-insights-a.jpg',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-a',
  'css' => 'gsb-insights-a.css',
  'regions' => array(
    'contentone' => t('Row A'),

    'contenttwoone' => t('Row B column 1 alpha'),
    'contenttwotwo' => t('Row B column 1 beta'),
    'contenttwothree' => t('Row B column 1 gamma'),
    'contenttwofour' => t('Row B column 2'),
    'contenttwofive' => t('Row B column 3'),

    'contentthreeone' => t('Row C column 1'),
    'contentthreetwo' => t('Row C column 2'),
    'contentthreethree' => t('Row C column 3 alpha'),
    'contentthreefour' => t('Row C column 3 beta'),
    'contentthreefive' => t('Row C gamma'),

    'contentfourone' => t('Row D column 1'),
    'contentfourtwo' => t('Row D column 2 alpha'),
    'contentfourthree' => t('Row D column 2 beta'),
    'contentfourfour' => t('Row D column 2 gamma'),
    'contentfourfive' => t('Row D column 3'),

    'contentfiveone' => t('Row E column 1'),
    'contentfivetwo' => t('Row E column 2'),
    'contentfivethree' => t('Row E column 3'),
    'contentfivefour' => t('Row E column 4'),

    'contentsixone' => t('Listing row')
  ),
);
