<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Insights One'),
  'icon' => 'gsb-insights-one.png',
  'category' => t('GSB'),
  'theme' => 'gsb-insights-one',
  'css' => 'gsb-insights-one.css',
  'regions' => array(
    'contentone' => t('Full Header'),
    'contenttwoone' => t('Column one'),
    'contenttwotwo' => t('Column two'),
    'contenttwothree' => t('Column three'),
    'contentthreeone' => t('Column one'),
    'contentthreetwo' => t('Column two'),
    'contentthreethree' => t('Column three'),
    'contentfourone' => t('Column one'),
    'contentfourtwo' => t('Column two'),
    'contentfourthree' => t('Column three'),
    'contentfiveone' => t('Column one'),
    'contentfivetwo' => t('Column two'),
    'contentfivethree' => t('Column three'),
    'contentfivefour' => t('Column four')
  ),
);
