<?php
// Plugin definition
$plugin = array(
  'title' => t('GSB Business insights'),
  'icon' => 'gsb-business-insights.png',
  'category' => t('GSB'),
  'theme' => 'gsb-business-insights',
  'css' => 'gsb-business-insights.css',
  'regions' => array(
    'fullheader' => t('Full Header'),
    'maintop' => t('Main Top'),
    'contenttwoone' => t('Column one'),
    'contenttwotwo' => t('Column two'),
    'contenttwothree' => t('Column three'),
    'mainquote' => t('Quote'),
    'contentfourone' => t('Column one'),
    'contentfourtwo' => t('Column two'),
    'contentfourthree' => t('Column three'),
    'mainbottom' => t('Main Bottom'),
    'quicklinks' => t('Quick Links'),
    'sidebar' => t('Sidebar'),
  ),
);
